kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: deploy-green-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 9081
    protocol: TCP
  - containerPort: 443
    hostPort: 9444
    protocol: TCP
- role: worker
  labels:
    tier: frontend
- role: worker
  labels:
    tier: backend
- role: worker
  labels:
    tier: database