apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vm-lb-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.1.200-172.16.1.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
